[project]
name = "app"
version = "1.0.0"
description = "A personal portfolio website built with Flask"
dependencies = [
    "flask",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"